Fix runtime browserify Error: Cannot find module 'dat-gui'
I guess browserify doesn't pickup "new require('foo')"? Changed to
separate require and new statements.